export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST';
export const CHAT_USER_SELECTION_CHANGE = 'CHAT_USER_SELECTION_CHANGE';
export const ON_MESSAGE_CHANGE ='ON_MESSAGE_CHANGE';
export const SAVE_MESSAGE = 'SAVE_MESSAGE';
export const NOTIFY_INCOMING_CHAT = 'NOTIFY_INCOMING_CHAT';